[package]
name = "crash_water"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
water_sim = {path = "../water_sim"}
nalgebra = "0.29.0"