[package]
name = "water_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.29.0"
bevy="0.8"
grid = {path = "../grid"}
zip = "0.6.2"